version = "1.0"

[main]
name = "Mautrix Signal configuration"

    [main.encryption]
    name = "Manage encryption"

        [main.encryption.allowed]
        ask = "Do you want to allow the use of encrypted room with Mautrix Signal Bridge? "
        type = "bololean"
        optional = false
        default = "0"
        help = "Allow encryption, work in group chat rooms with e2ee enabled"

# TODO: Add toggle for enabling and enforcing encyption