version = "1.0"

[encryption]
name = "Encryption"
services = ["__APP__"]
    [encryption.config]
    name = "Encryption settings"

        [encryption.config.encryption]
        ask = "Enable encryption"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Enables end to bridge encryption"
        bind = "encryption>allow:__FINALPATH__/config.yaml"
