version = "1.0"

[bind]
name = "Mautrix Signal configuration"

    [bind.encryption]
    name = "Manage encryption"

        [bind.encryption.encryption]
        ask = "Do you want to allow the use of encrypted room with Mautrix Signal Bridge? "
        type = "boolean"
        help = "Allow encryption, work in group chat rooms with e2ee enabled. Values possible are 'true' or 'false'."
        bind = ":__FINALPATH__//config.yaml"


# TODO: Add toggle for enabling and enforcing encyption