#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

function get__encryption {
    encryption=$(ynh_app_setting_get --app $app --key encryption)
    echo "'${encryption}'"
}
#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_run $1
