#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

synapse_db_name="$(get_synapse_db_name $synapse_instance)"
bot_synapse_db_user="@$botname:$server_name"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Removing the PostgreSQL configuration..."

# Remove permissions of app to the synapse db
ynh_psql_db_shell "$synapse_db_name" <<< "DROP OWNED BY \"$app\";"

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# TODO: check if there is a data dir or some files to remove

# Remove a directory securely
ynh_safe_rm "/etc/matrix-$synapse_instance/app-service/$app.yaml"
/opt/yunohost/matrix-$synapse_instance/update_synapse_for_appservice.sh || ynh_die "Synapse can't restart with the appservice configuration"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
